project_id = "ihqogooddvhsvfhbwdez"

[functions.r2-upload]
verify_jwt = true

[functions.admin-reset-user-password]
verify_jwt = false

[functions.admin-impersonate-user]
verify_jwt = false

[functions.register-deploy]
verify_jwt = false

[functions.google-drive-proxy]
verify_jwt = false

[functions.eventos-aviso]
verify_jwt = false
