// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List events from the ANA Brasil calendar visible to the signed-in user. Respects the app's row-level security. Returns up to `limit` rows ordered by start date.",
  inputSchema: {
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 100)."),
    from: z.string().optional().describe("ISO date/datetime lower bound for start_datetime (inclusive)."),
    to: z.string().optional().describe("ISO date/datetime upper bound for start_datetime (inclusive)."),
    unit: z.string().optional().describe("Filter by organizing unit."),
    status: z.string().optional().describe("Filter by event status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, from, to, unit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const cappedLimit = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("events").select(
      "id,title,description,unit,status,start_datetime,end_datetime,location,created_at"
    ).is("deleted_at", null).order("start_datetime", { ascending: true }).limit(cappedLimit);
    if (from) query = query.gte("start_datetime", from);
    if (to) query = query.lte("start_datetime", to);
    if (unit) query = query.eq("unit", unit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event",
  description: "Fetch a single event by id, including its full metadata. Respects row-level security.",
  inputSchema: {
    id: z2.string().uuid().describe("Event UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("events").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Event not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/me.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var me_default = defineTool3({
  name: "me",
  title: "Current user",
  description: "Return the signed-in user's profile: name, email, unit, permission level and role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const [profileRes, roleRes] = await Promise.all([
      client.from("profiles").select("name,email,unit,permission_level,is_active,delegated_units,bond_type").eq("user_id", userId).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profileRes.data?.email ?? null,
      profile: profileRes.data ?? null,
      role: roleRes.data?.role ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var supabaseUrl = "https://supabase.anabrasil.org".replace(/\/+$/, "");
var mcp_default = defineMcp({
  name: "ana-brasil-mcp",
  title: "ANA Brasil MCP",
  version: "0.1.0",
  instructions: "Tools for the ANA Brasil events platform. Use `me` to inspect the signed-in user, `list_events` to browse the calendar (with optional date/unit/status filters), and `get_event` to fetch a specific event by id. All calls run as the connected user and respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl}/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [me_default, list_events_default, get_event_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
